/**
 * This component handles password reset functionality for users who
 * have clicked a password reset link from their email.
 *
 * The link contains a token in the query string (`?token=...`), which
 * is validated and used to authorize the password change.
 *
 * This form allows the user to input a new password, which is sent
 * along with the token to the backend to update the account.
 */

import React, { useMemo, useState } from 'react';
import axios from 'axios';
import { useLocation, useNavigate } from 'react-router-dom';
import './FormStyles.css';

export default function ResetForgottenPassword() {
  const [newPassword, setNewPassword] = useState('');
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const location = useLocation();
  const navigate = useNavigate();

  /**
     * Extract the reset token from the URL query string.
     * This token was generated by the backend and sent via email.
     * It must be provided for the password reset to succeed.
  */
  const token = useMemo(() => {
    const qp = new URLSearchParams(location.search);
    return (qp.get('token') || '').trim();
  }, [location.search]);

  /**
     * Form submission handler.
     * Sends the new password and token to the backend to reset the user's password.
  */
  const handleReset = async (e) => {
    e.preventDefault();

    // Ensure token is present (should always be if user clicked reset link)
    if (!token) {
      setMessage('Invalid reset link. Please request a new one.');
      return;
    }
    if (!newPassword) {
      setMessage('Please enter a new password.');
      return;
    }

    setSubmitting(true);
    setMessage('Updating password...');

    try {
      // Send token as query param; password in body
      const res = await axios.post(
        '/api/auth/change-password',
        { password: newPassword },
        { params: { token } }
      );

      // Show success message and redirect to login page
      setMessage(res.data || 'Password changed successfully.');
      // Small pause then redirect to login
      setTimeout(() => navigate('/login'), 1500);
    } catch (err) {
      const apiMsg =
        err.response?.data ||
        err.message ||
        'Failed to reset password.';
      setMessage(apiMsg);
      setSubmitting(false);
    }
  };

  return (
    <div className="auth-form">
      <h2>Reset Password</h2>

      {!token && (
        <p className="submit-message error">
          Invalid or missing token. Please request a new reset link.
        </p>
      )}

      {message && <p className="submit-message">{message}</p>}

      <form onSubmit={handleReset}>
        <input
          type="password"
          placeholder="Enter new password"
          value={newPassword}
          onChange={(e) => setNewPassword(e.target.value)}
          disabled={submitting || !token}
          required
        />
        <button type="submit" disabled={submitting || !token}>
          {submitting ? 'Updating…' : 'Update Password'}
        </button>
      </form>
    </div>
  );
}
